version: "3"
services:
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        ports:
            - '3000:3000'
            - '80:80'
            - '81:81'
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        ports:
            - '3001:3001'
        depends_on: 
            - backend